on:
  workflow_dispatch:
  schedule:
    - cron: '45 13 */6 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/st1ll2@cron
        with:
          token: ${{ secrets.token }}
